version: '3.9'

networks:
  app-network:
    name: app-network
    driver: bridge
    external: true

services:
  mongo:
    image: mongo:6.0.5
    container_name: app-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - ${MONGODB_PORT:-27017}:27017
    networks:
      - app-network
    volumes:
      - $PWD/docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - app-mongo_db:/data/db/
      - app-mongo_configdb:/data/configdb/

  redis:
    image: redis:alpine
    container_name: app-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 3s
    command:
      - '--maxmemory 128M'
    networks:
      - app-network
    volumes:
      - app-redis_data:/data/
    depends_on:
      - mongo

  php:
    build:
      context: $PWD/docker/php
      target: php_app
    container_name: app-php
    networks:
      - app-network
    volumes:
      - $PWD/docker/php/conf/php.ini:/usr/local/etc/php/conf.d/docker.ini
      - $PWD/:/var/www/html/
    environment:
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_PORT: ${MONGODB_PORT}
    env_file:
      - .env.app
    depends_on:
      - mongo
      - redis

  supervisor:
    build:
      context: $PWD/docker/php
      target: php_supervisor
    container_name: app-supervisor
    command: supervisord -n
    networks:
      - app-network
    volumes:
      - $PWD/docker/supervisor/conf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - $PWD/:/var/www/html/
    environment:
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_PORT: ${MONGODB_PORT}
    env_file:
      - .env.app
    depends_on:
      - mongo
      - redis
      - php
    deploy:
      resources:
        limits:
          memory: 1G

  nginx:
    image: nginx:alpine
    container_name: app-nginx
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME:-nginx-srv}
    ports:
      - ${NGINX_HTTP_PORT:-80}:80
      - ${NGINX_HTTPS_PORT:-443}:443
    networks:
      - app-network
    volumes:
      - $PWD/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/docker/nginx/templates/:/etc/nginx/templates/
      - $PWD/docker/nginx/ssl/:/etc/nginx/ssl/
      - $PWD/:/var/www/html/
    depends_on:
      - php

volumes:
  app-mongo_db:
    name: app-mongo_db
  app-mongo_configdb:
    name: app-mongo_configdb
  app-redis_data:
    name: app-redis_data
    driver: local
